name: back_on_track_app_2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '3.4.3'

dependencies:
  cloud_firestore: ^5.1.0
  firebase_core: ^3.2.0
  firebase_database: ^11.1.1
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_bluetooth_serial: ^0.4.0
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0
  intl: ^0.19.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
